// <auto-generated />
using System;
using CarRentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRentService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210911115306_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataModel.Models.AccountStatus", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AccountApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("BankApproved")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("AccountStatuses");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e575",
                            AccountApproved = false,
                            BankApproved = false
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e571",
                            AccountApproved = false,
                            BankApproved = false
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e579",
                            AccountApproved = false,
                            BankApproved = false
                        });
                });

            modelBuilder.Entity("DataModel.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9450e900",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9450e901",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9450e909",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("DataModel.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9450e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c9e06d7-814c-41d4-b881-829bb8894509",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "admin@dotnet.project",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DOTNET.PROJECT",
                            NormalizedUserName = "ADMIN@DOTNET.PROJECT",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ19lcpUMdhBcvdxl8qTASubgNoRqS98NhjMsgmRZLvf0gC6fvVEf+Kx82yt6HA46Q==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ea2860fe-ea66-4782-8547-0fd03772a863",
                            TwoFactorEnabled = false,
                            UserName = "admin@dotnet.project"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9450e571",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14b02f68-8d0a-4308-bc73-d0935d9048c9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "demouser@dotnet.project",
                            EmailConfirmed = true,
                            FirstName = "Demo",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMOUSER@DOTNET.PROJECT",
                            NormalizedUserName = "DEMOUSER@DOTNET.PROJECT",
                            PasswordHash = "AQAAAAEAACcQAAAAEAmn76sUvGPXCaRv/70o10o7p0mCBrGtgC1cTVTdndYkNKzM3cwAy3QfS6/S1xfKEw==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ad7cb3d8-80f0-4f4b-b912-459983d2a6c1",
                            TwoFactorEnabled = false,
                            UserName = "demouser@dotnet.project"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9450e579",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee7789e5-6f1c-42ea-9d6d-b0c98292975e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "demoadmin@dotnet.project",
                            EmailConfirmed = true,
                            FirstName = "Demo",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMOADMIN@DOTNET.PROJECT",
                            NormalizedUserName = "DEMOADMIN@DOTNET.PROJECT",
                            PasswordHash = "AQAAAAEAACcQAAAAEHLl5Gu57A+8UvZtuzkSGnuuAxXGMtGbNCo0Neja9hqybF3bUdtwFu/H7MFTkQLl3Q==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4b8da353-6bf6-4e66-a338-2513537e3fb3",
                            TwoFactorEnabled = false,
                            UserName = "demoadmin@dotnet.project"
                        });
                });

            modelBuilder.Entity("DataModel.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e575",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9450e900"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e571",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9450e901"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e579",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9450e909"
                        });
                });

            modelBuilder.Entity("DataModel.Models.FormSubmitted", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("BankFormSubmit")
                        .HasColumnType("bit");

                    b.Property<bool>("IdentityFormSubmit")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("FormSubmitteds");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e575",
                            BankFormSubmit = false,
                            IdentityFormSubmit = false
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e571",
                            BankFormSubmit = false,
                            IdentityFormSubmit = false
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e579",
                            BankFormSubmit = false,
                            IdentityFormSubmit = false
                        });
                });

            modelBuilder.Entity("DataModel.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatetAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DocType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Message")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("DataModel.Models.UserAdditionalInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdditionalEmail")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("UserAdditionalInfos");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e575"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e571"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9450e579"
                        });
                });

            modelBuilder.Entity("DataModel.Models.UserBankDetails", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BankName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BankSwiftCode")
                        .HasColumnType("varchar(100)");

                    b.HasKey("AppUserId");

                    b.ToTable("UserBankDetails");

                    b.HasData(
                        new
                        {
                            AppUserId = "a18be9c0-aa65-4af8-bd17-00bd9450e575"
                        },
                        new
                        {
                            AppUserId = "a18be9c0-aa65-4af8-bd17-00bd9450e571"
                        },
                        new
                        {
                            AppUserId = "a18be9c0-aa65-4af8-bd17-00bd9450e579"
                        });
                });

            modelBuilder.Entity("DataModel.Models.VerificationTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("DataModel.Models.VerifyAppuser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerifyAppusers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DataModel.Models.AccountStatus", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", "User")
                        .WithOne("AccountStatus")
                        .HasForeignKey("DataModel.Models.AccountStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationUserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DataModel.Models.FormSubmitted", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", "User")
                        .WithOne("FormSubmitted")
                        .HasForeignKey("DataModel.Models.FormSubmitted", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Models.Notification", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("DataModel.Models.UserAdditionalInfo", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", "User")
                        .WithOne("UserAdditionalInfo")
                        .HasForeignKey("DataModel.Models.UserAdditionalInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Models.UserBankDetails", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", "User")
                        .WithOne("UserBankDetails")
                        .HasForeignKey("DataModel.Models.UserBankDetails", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Models.VerificationTokens", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Models.VerifyAppuser", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", "User")
                        .WithMany("VerifyAppusers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataModel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.Models.ApplicationRole", b =>
                {
                    b.Navigation("ApplicationUserRole");
                });

            modelBuilder.Entity("DataModel.Models.ApplicationUser", b =>
                {
                    b.Navigation("AccountStatus");

                    b.Navigation("ApplicationUserRole");

                    b.Navigation("FormSubmitted");

                    b.Navigation("Notifications");

                    b.Navigation("Tokens");

                    b.Navigation("UserAdditionalInfo");

                    b.Navigation("UserBankDetails");

                    b.Navigation("VerifyAppusers");
                });
#pragma warning restore 612, 618
        }
    }
}
